### ISSUE TITLE
 Deprecated: The each() function is deprecated

### ISSUE THREAD

**Issue by jammin88** [turtledesign/royalmail-php#12]
Running on PHP 7.2, looks like each() function is now deprecated and gives a warning:

`Deprecated: The each() function is deprecated. This message will be suppressed on further calls in /vendor/turtledesign/royalmail-php/src/Validator/Validates.php on line 31`

**Comment by Buntix** [comment]
This should be fixed in the master branch all releases from 0.3.1.4 onwards  (worth noting that the older versions start v0.#### but GitHub lists them at the top of the tags dropdown. 0.4.0.1 is the latest).

Cheers,
Stefan

**Comment by jammin88** [comment]
Ah, correct - my apologies, was running an older version.

**Comment by jammin88** [comment]
Hmm ok, updating however throws up a new issue for us...

$raw_response->asArray(); now returns an empty array.... This code worked on previous version?

**Comment by Buntix** [comment]
That should be fixed now with the update https://github.com/turtledesign/royalmail-php/commit/750c4277bcff5466ac73927ece8aae439b74efde

Version 0.4.0.2 with composer.
