### ISSUE TITLE
Wrong version issue with basic request

### ISSUE THREAD

**Issue by krio** [turtledesign/royalmail-php#6]
Is the library working with the latest onboarding version? I'm trying a simple script based on examples here and it seems like it won't authenticate. I get "Wrong Version" and then lower in the request it says client id missing. In the library examples it says to use a username and password so shouldn't it convert those into the headers that royal mail wants to see like client id and secret?

Thanks!

```
<?php
require_once 'vendor/autoload.php';

$interface  = new \RoyalMail\RoyalMail([
    'mode'           => 'onboarding',
    'application_id' => '---',
    'transaction_id' => '123456',
    'username'       => '---',
    'password'       => '---',
]);

$response = $interface->createShipment([
    'requestedShipment' => [
        'shipmentType'    => 'Delivery',
        'serviceType'     =>  'T',
        'serviceOffering' => 'TRM',

        'recipientContact' => [
            'name' => 'Mr Tom Smith',
        ],

        'recipientAddress' => [
            'addressLine1' => '44-46 Morningside Road',
            'postTown'     => 'Edinburgh',
            'postcode'     => 'Eh10 4Bf',
        ],
    ]
]);

echo "<pre>";
print_r($response);
```

```
[response] => 
  401
  Unauthorized
  Client id missing.
```

```
[errors:protected] => Array
        (
            [0] => Array
                (
                    [message] => API Connection Error: more details available in debug info.
                )

        )

    [warnings:protected] => Array
        (
        )

    [succeeded:protected] => 
    [debug_info:protected] => RoyalMail\Exception\ResponseException Object
        (
            [debug_info:protected] => Array
                (
                    [exception] => SoapFault Object
                        (
                            [message:protected] => Wrong Version
```

**Comment by Stuart1066** [comment]
I was just about to post the same problem as I'm getting exactly the same error. I've spoken to Royal Mail and it appears that the request needs to contain the client id and secret in the request header together with the username and password in the SOAP header. This was the example post that RM sent me a few minutes ago:

```
POST https://api.royalmail.net/shipping/v2 HTTP/1.1
Accept-Encoding: gzip,deflate
Content-Type: text/xml;charset=UTF-8
SOAPAction: "createShipment"
X-IBM-Client-Secret: XXXX // Client Secret value should be inserted here.
X-IBM-Client-ID: XXXX // Client ID inserted here.
Content-Length: 3766
Host: api.royalmail.net
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.1.1 (java 1.5)

<soapenv:Envelope xmlns:oas="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd" xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:v1="http://www.royalmailgroup.com/integration/core/V1" xmlns:v2="http://www.royalmailgroup.com/api/ship/V2">
   <soapenv:Header><wsse:Security xmlns:wsse="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd"><wsse:UsernameToken wsu:Id="UsernameToken-11B848317B46149A2514574342988913"><wsse:Username>XXXX</wsse:Username><wsseassword Type="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-username-token-profile-1.0#PasswordDigest">5CB8w7tx/XxsMi/U0pThGvaC3fQ=</wsseassword><wsse:Nonce EncodingType="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-soap-message-security-1.0#Base64Binary">XXXX</wsse:Nonce><wsu:Created>2016-03-08T10:51:38.891Z</wsu:Created></wsse:UsernameToken></wsse:Security> // Username encoded as password digest.
</soapenv:Header>
```

I can see my post header does not contain the client id and secret and I cannot see where to add them or how to change the code to add them. I think that this is what is missing.

```
POST /shipping/v2 HTTP/1.1
Host: api.royalmail.net
Connection: Keep-Alive
User-Agent: PHP-SOAP/7.0.2-4+deb.sury.org~trusty+1
Content-Type: text/xml; charset=utf-8
SOAPAction: "createShipment"
Content-Length: 1686
```

**Comment by krio** [comment]
Thanks Stuart. I'm seeing the same thing. I'm going to mess around with this later today and will let you know if I come up with anything. Please do the same if you figure it out.

**Comment by krio** [comment]
I'm still having issues, but I'm able to get the client id and secret into the http header by using the following. I'm getting an internal server error now though, instead of client id missing. The library will merge these settings into the soap call http headers and send them. Still working on it... Put this alongside the application id etc...

```
'soap_client_options' => array(
        'stream_context' => stream_context_create(
            array(
                'http' =>
                    array(
                        'header'           => implode(
                            "\r\n",
                            array(
                                'Accept: application/soap+xml',
                                'X-IBM-Client-Id: ' . '---',
                                'X-IBM-Client-Secret: ' . '----'
                            )
                        ),
                    ),
            )
        )
    )
```

**Comment by Stuart1066** [comment]
Thanks for the updates. I had come up with the same solution except I was trying to use an array for the header as the documentation appeared to say it would accept a numbered array. Anyway I've tried your solution and it does add the headers that look correct and appear to be interpreted correctly by the RM onboarding system. However if I put in my correct client id and secret I get a '502 Bad Gateway' error from nginx. I was unsure about the Accept header so I tried without that and got the same result. If I change my client id or secret to be incorrect values I get the errors 'Client id not registered' and 'Invalid client id or secret' so I think the RM server is certainly reading the client id correctly.

I did a network trace of the traffic between my server and the RM server and I see the same sort of conversation when correct or incorrect values are used. The traffic contents are encrypted so unfortunately I can't see the contents.

My first attempts were trying a createShipment which I could see had not been successful when I checked the onboarding DMO site. I then manually created a shipment on the onboarding DMO site and tried a cancelShipment but that produced the same errors and the shipment was not cancelled.

I checked the nginx error log file and each time it fails I get the following log entry:

`2016/11/04 20:44:31 [error] 840#840: *417 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 192.168.10.1, server: homestead.app, request: "GET /rm_api.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.0-fpm.sock:", host: "homestead.app"`

I'm afraid I don't know where to go next with this if you have any ideas then let me know. My only thought is that there is mention of a client certificate and I don't have one, do you? I can speak to Royal Mail next week and see if they can check the logs on the onboarding system.

**Comment by krio** [comment]
I'm currently getting an authorization error. Is the api username and
password something that they send separately? I know the client id and
secret are correct because I get a different error for that when I change
it.

I haven't received the bad gateway error yet. When I'm back later I will
post my test script and you can try copying it and maybe I've got something
in there you don't. If you want post yours and I'll try it as well. Just
make sure to hide the credentials.

**Comment by Stuart1066** [comment]
I now have it working! 

The username and password are different from the client id and secret.  I registered on developer.royalmail.net, then on that site registered a new application and applied to use the Shipping API with that app. At that point the client id and client secret are displayed. I then received an email from Royal mail to say that my use of the API was approved and for the API it gave me a username, password, application id and end point. The first three items are required when you setup the connection, see below, and the end point was the address of the onboarding system which royalmail-php already has if you set 'mode' => 'onboarding'. The other details in the email were the username and password for the onboarding DMO site so you can check the shipments you create. When you use the onboarding DMO site and select Shipment \ Current Shipments you need to check 'Show Shipments for All Users' to see the shipments created through the API.

My working code is:

``` <?php
require __DIR__ . '/../vendor/autoload.php';

$interface = new \RoyalMail\RoyalMail([
    'mode' => 'onboarding',
    'application_id' => 'API application id from Royal Mail email',
    'transaction_id' => '1',
    'username' => 'API username from Royal Mail email',
    'password' => 'API password from Royal Mail email',
    'soap_client_options' => array(
        'stream_context' => stream_context_create(
            array(
                'http' =>
                    array(
                        'header' => implode(
                            "\r\n",
                            array(
                                'X-IBM-Client-Secret: ' . 'client secret from developer.royalmail.net',
                                'X-IBM-Client-Id: ' . 'client id from developer.royalmail.net'
                            )
                        ),
                    ),
            )
        )
    )
]);

$response = $interface->createShipment([
    'requestedShipment' => [
        'shipmentType' => 'Delivery',
        'serviceType' => '2',
        'serviceOffering' => 'CRL',
        'serviceFormat' => 'F',
        'shippingDate' => '2016-11-05',
        'recipientContact' => [
            'name' => 'Mr Tom Smith',
        ],

        'recipientAddress' => [
            'addressLine1' => '44-46 Morningside Road',
            'postTown' => 'Edinburgh',
            'postcode' => 'EH10 4BF',
        ],
        'items' => [
            'item' => [
                'numberOfItems' => 1,
                'weight' => [
                    'value' => 0,
                    'unitOfMeasure' => [
                        'unitOfMeasureCode' => 'g'
                    ]
                ]
            ]
        ]
    ]
]);
```

I can now create and cancel shipments and see the response, errors and warnings however there does appear to be something not quite right. The thing that caused my '502 Bad Gateway' error was var_dump($response) at the end of my code. $response is an object of class RoyalMail\Response\Interpreter that doesn't like being dumped.

**Comment by krio** [comment]
Thanks! I'm waiting on the username and password as I can't find that email anywhere, so I'll close this out.
