### ISSUE TITLE
Installation failed, incompatible symfony/yaml version

### ISSUE THREAD

**Issue by joekersh** [turtledesign/royalmail-php#9]
My project already includes symfony/yaml v 3.3.16.0 and when running:

composer require 'turtledesign/royalmail-php:*@dev'

The installation fails. Looks like the composer file will only allow symfony/yaml up to 3.0.9, no higher.

Is there a reason for this?

Thanks

**Comment by Buntix** [comment]
I've updated the composer requirement to 

"symfony/yaml":    ">=2.7"

I'd just specified it badly before.  I've tested it up to the current

"dev-master": "4.0-dev" version.

**Comment by joekersh** [comment]
Updating Laravel to 5.6 allowed a successful install in the end, i was running 5.3, but thanks anyway as this will solve the problem for anyone else!
